### PR TITLE
[RFR] Update translations

### PR DESCRIPTION
**Pull request by morckx**

### CODE REVIEW

**Comment by zo-shin** [comment]
1 - Some translatable strings are wrongly marked with the untranslatable attribute. Only "**media_route_menu_title**", "**app_id**" and "**settings_radiobrowser_servers_default**" should be marked as untranslatable.
2 - I do believe that some new strings are generated by an app rather than an app user because they are totally incorrect. We shouldn’t depend on any app-generated strings when it comes to a serious job. If no one is responsible for them, just let them be.

**Comment by morckx** [comment]
> 1 - Some translatable strings are wrongly marked with the untranslatable attribute. Only "**media_route_menu_title**", "**app_id**" and "**settings_radiobrowser_servers_default**" should be marked as untranslatable.

I've also marked those that are (without context) not translatable automatically, like e. .g. "port number".

> 2 - I do believe that some new translation strings were generated by an app rather than an app user because they are totally incorrect. We shouldn’t depend on any app-translated strings when it comes to a serious job. If no one is responsible for them, just let them be.

The problem is that at seems that currently we only have active human translators for German, Chinese, and Danish. For all other languages the settings will be a mix of a growing percentage of English and a decreasing few of them for the native locale. Should we drop translations for the unmaintained locales 
altogether?

For the languages I know more or less (German, French, Spanish), I spotted only a few weak but tolerable automatic translations (after updating the untranslatable attributes). This and the hope that bad translations will activate more human translator support, so that we can fix the mistakes afterwards, made me dare  this RFR. :)

Maybe we could also get a license for a commercial translation API (like deepl).

**Comment by zo-shin** [comment]
1 - Why is "port" untranslatable?
2 - If a certain language is inactive for a long time, it means very few users pay attention to it or the mixed languages don’t affect the local users at all, so I don’t think bad translations will attract anyone. Strings in apps are serious, we shouldn’t allow any ridiculous one in it. Take the Chinese translations for instance, it took “appearance” for “come out”, “interaction” for “mutual impact”, which are not tolerable and will ruin the app. As I said, any app-translated strings are not dependable.
I have been considering if all the languages are really useful and if any of them should be removed. To improve the image of the app, I would erase the languages updated earlier than two years ago if i were the developer.

**Comment by morckx** [comment]
> 1 - Why is "port" untranslatable?

It was sometimes translated in the sense of harbour (only), as far as I remember.

> 2 - If a certain language is inactive for a long time, it means very few users pay attention to it or the mixed languages don’t affect the local users at all, so I don’t think bad translations will attract anyone. 

I meant attracting existing users to become active in translation.

> Strings in apps are serious, we shouldn’t allow any ridiculous one in it. Take the Chinese translations for instance, it took “appearance” for “come out”, “interaction” for “mutual impact”, which are not tolerable and will ruin the app. As I said, any app-translated strings are not dependable.

For German and French the translations were almost perfect, but we could also just keep and improve the languages anyone active here knows.

> I have been considering if all the languages are really useful and if any of them should be removed. To improve the image of the app, I would erase the languages updated earlier than two years ago if i were the developer.

Yes, I'd also regard this as a viable option. Just to have 10% translated is about as bad as 5% bad translations.

**Comment by zo-shin** [comment]
OK if you think it's acceptable. I'll correct those wrong strings after it's merged.

**Comment by segler-alex** [comment]
i would not delete existing translations. it would invalidate the work of people who already helped, in many open source projects  there are translations in different completion levels. every added string in the code does lower the completion of every translation.
i will never invest money in translations. i already pay for the servers.

**Comment by werman** [comment]
I would agree that bad translation is worse than no translation. Automatic translation work great with some languages but doesn't work for others. Also even old translation is useful because it probably contains common strings which user sees the most.

I think we have strings that are are highly visible to users and greater amount of strings (in settings) which users don't often interact and which tend to be long. Therefor the main focus of translation should be on small subset of strings.

Recently I saw a website https://i18ns.com/ with translations of common strings in context of different apps - I think it could help us with common strings.

I will update Russian and add Ukrainian translations when things stabilize.

**Comment by morckx** [comment]
You all have convinced me. The accuracy of the identifiers in the settings should remain within a controllable range.

I  will close this pull request and will make a new one, limited to a manually controlled German localization.

> Recently I saw a website https://i18ns.com/ with translations of common strings in context of different apps - I think it could help us with common strings.

Nice idea and nice API, however for German and French at least, the top results are worse than in this pull request. So we would need to know a few sufficiently freely licensed apps that we know are only manually localized to get ahead.

**Pull request closed without merging**
