### PR TITLE
Improve stations list design, image loading and caching, add clickable tags to station, add ability to copy stream url

### PR DESCRIPTION
**Pull request by werman**
I have made a lot of UI improvements and offloaded image loading and caching to external dependency 'Picasso'. I changed a name of country to its flag which reduced text amount in item and I think made it visually better. All changes added approx 400kb to the final apk.

Sorry for such huge commit - it was late to separate it when I realised this.

Screenshots:

new_station_list

station_url

Changelog:

- replace custom solution for loading and caching images with Picasso dependency.
- change ListView into RecyclerView as a modern way to handle lists and to support expandable stations.
- change station items design to follow material guidelines, add country flag and restrict tags textview to one line.
- add expanded state of station items which has clickable tags and several actions for given station instead of having popup menu.
- add copy stream url to clipboard.
- improve restoring last application state.

### CODE REVIEW

**Comment by Wikinaut** [comment]
👍 works for me; looks nice; well done! 🥇

**Comment by Wikinaut** [comment]
@werman remark: apparently, you dropped the coding type information (mp3/ogg/aac). Please can you re-add it?

**Comment by segler-alex** [comment]
Ist Picasso free Software? Ich am asking because of fdroid Support for it.

**Comment by Wikinaut** [comment]
@segler-alex look: https://www.startpage.com/do/search?q=Picasso%20android and https://square.github.io/picasso/#license I suppose this is what @werman uses, but I'm not 100% sure.

**Comment by werman** [comment]
@Wikinaut Thanks! I'll add coding info to expanded station state.

@segler-alex As @Wikinaut guessed I'm using https://github.com/square/picasso which has Apache License v2.0.

Also flags were taken from https://github.com/googlei18n/region-flags which takes them from wikipedia:

> The flags are downloaded from Wikipedia. When Wikipedia flags were copyrighted, we worked we Wikipedia editors to either relicense them, or drew / sourced and uploaded new public-domain versions.

**Comment by Wikinaut** [comment]
👎 
#### Regression

I discovered a problem with your patch:

when a station is playing, and when you then click the RadioDroid-App Icon again, the stream is stopped.

**Comment by werman** [comment]
@Wikinaut thanks, I'll look into it.

**Comment by Wikinaut** [comment]
Pls. let me know, when/if you can confirm my observation.

**Comment by werman** [comment]
@Wikinaut Everything works perfectly on latest LineageOs 14.1 (android 7.1), crashes on android 4.1.1 in ActivityMain.onNewIntent because intent.getExtras() == null. Will add check for null.

**Comment by Wikinaut** [comment]
He @werman compliments again, great job !! Looked to the code, wow.

**Pull request merged**
