### PR TITLE
moved the start-autoplay setting from player menu to interaction menu

### PR DESCRIPTION
**Pull request by Wikinaut**
I moved the autoplay-setting to the interaction menu
+ also set the default value to "true"

### CODE REVIEW

**Comment by werman** [comment]
> also set the default value to "true"

Why? Isn't this an option which will make the station play when app is started without user interaction?

**Comment by Wikinaut** [comment]
@werman 
> Why? Isn't this an option which will make the station play when app is started without user interaction?
Yes, I set this to "true", so that once the app is installed, it starts a station (if one has been played before).

**Comment by werman** [comment]
I don't think that starting playback on app startup is a good idea. In most cases user expects apps not to play audio or video without explicit user agreement (unless it's an ad but they just work against user, or twitch...) for many reasons: unexpected loud sounds, playing something you don't want others to hear, bandwith usage. Having the option for autoplay is good, making it default is not be ause users will be quite confused.

**Comment by Wikinaut** [comment]
@werman Once you selected a station for a very first time - this plays it already. So then the user adjusts the volume. I think your statement is overcomplicating the situation.

**Comment by werman** [comment]
Maybe I'm misunderstanding something. Ok, with this option if I'm opening the app (I have a station in history) will it start playing this station without my input?

**Comment by Wikinaut** [comment]
@werman Yes. But then you can opt-out. (Before my change, it was an "opt-in".)

**Comment by werman** [comment]
Opting-out out of unintuitive bahaviour isn't good, most users have real troubles navigating the settings thus defaults shouldn't be against them, playing sounds without user consent is  something unexpected.

**Comment by Wikinaut** [comment]
When I switch my DAB radio on, or my old FM radios or my TV, it always start playing with the last station and the last volume setting. Sorry, that's how it is.

**Comment by werman** [comment]
Youtube doesn't autoplay video when I enter it, music apps don't play music when I launch them, I didn't see other radio apps auto play stations (I didn't see many so I can be mistaken here). I understand your comparison but RadioDroid is an application first and users expect it to behave similar to other apps.

**Comment by werman** [comment]
The ideal solution would be to have a popup with several common settings including this one which will be shown e.g. on a second app launch.
However I'm absolutely against having autoplay enabled by default (however I'm not completely against having it by default play only when headphones are plugged).

**Comment by morckx** [comment]
I also think it's too risky to enable auto-play by default.

**Comment by morckx** [comment]
As a place for the auto-play setting, I would suggest a new category "Start-up behaviour", which should have the standard launch (or rocket or airplane take-off) icon should also include "Start action". This would allow users to find it more easily, I guess.

That was actually my original intention (https://github.com/segler-alex/RadioDroid/issues/507#issuecomment-498061356 ). I had only decided against it, because the category then only contains 2 items.

**Comment by Wikinaut** [comment]
@morckx Do you mean these two entries in a new category

* auto-play when starting the App
* start with one of the lists (favorites, search, history) ?

**Comment by Wikinaut** [comment]
@zo-shin and @werman would you support this change as suggested by @morckx?

**Comment by werman** [comment]
Yes

**Comment by zo-shin** [comment]
I prefer keeping what it is, but I’m not against the new suggestion.

**Comment by morckx** [comment]
Like this? Or rather under "Interaction"? In addition, I'd also change "Start action" to "Start display", or what do you think? 

Startup_RadioDroid

**Comment by zo-shin** [comment]
I prefer keeping **start action** under **interaction**, **auto-play** under **player**, but I’m not against your new changes.

**Comment by zo-shin** [comment]
And I think **recordings** and **music player daemon** can be moved into other options, because both of them only contain one item .

**Comment by morckx** [comment]
> And I think **recordings** and **music player daemon** can be moved into other options, because both of them only contain one item .

 **recordings** will probably very soon get **Pre-Recording Buffer** or something like that as an additional option. **MPD** could, as far as I'm concerned,  be moved to **Connectivity**, but I have no idea what else is planned there.

**Comment by zo-shin** [comment]
OK, not bad.

**Pull request merged**
