### PR TITLE
add refresh on history and favorites tab

### PR DESCRIPTION
**Pull request by segler-alex**
I added a refresh feature to the history and the favorites tab.
It should get rid of stations that are not in the database anymore and also does update entries from the webservice.

### CODE REVIEW

**Comment by werman** [comment]
I think it would be better to have an explicit trigger for such action, like "Remove Invalid Stations" in the menu. Because triggering it by a swipe most likely would be confusing for the user, especially if some stations would be deleted as a result.

Or with swipe-to-refresh just visibly mark such invalid stations. However, it isn't worth the hassle.

**Comment by segler-alex** [comment]
stations that are not in the database any more, do not play anymore anyway, so i thougth, i could remove them. 
they are not usable anymore for playing. i think it would be cool to display a list to the user what stations have been deleted, but i did not know how.

I liked the refresh swipe, because it does say basically what it is. it is a refresh. it refreshes for example icons if they changed or the up/down tendency of the clicks.  it makes the lists more consistent, every list has now a refresh swipe. i like this a lot.

i always wanted to do the refresh swipe for the status page in the settings also, but i did not know how to add the swipe there.

**Comment by segler-alex** [comment]
maybe it is a good idea to just mark them in the list, how would you acomplish this? i would add a separate field "deleted" in the DataRadioStation class, but i do not know how to display it in the list, or change the item

**Comment by werman** [comment]
So the removed stations are only the ones which cannot be played? If so, then I think a toast with a message that stations were removed due to them being invalid would suffice (I just generally don't like when applications remove something without even notifying me). Thanks.

**Comment by werman** [comment]
> maybe it is a good idea to just mark them in the list, how would you acomplish this? i would add a separate field "deleted" in the DataRadioStation class, but i do not know how to display it in the list, or change the item

If you want to go with this route - changing the background color of the stations to e.g. light red could be a reasonable solution (also with a toast that X stations are found invalid).

**Pull request merged**
