### PR TITLE
Added BottomNavigationView

### PR DESCRIPTION
**Pull request by avently**
- now BottomNavigationView is a default navigation. NavigationView is here too if someone likes it more.
- so many code changes. Made it more readable & clean & awesome.
- "About" and "Statistic" were removed from menu and were placed in Settings. 
- "Recordings" button now located in the menu (for NavigationView) and in the mini player (for BottomNavigationMenu).

@segler-alex @werman @Wikinaut  what chipset your devices have? My phone is on MTK chipset and I have problems with speed of fragments. Its opens with a delay <=500ms.  Seems like list_item_station is not optimized. Do you have such problems too?

### CODE REVIEW

**Comment by werman** [comment]
I have Nexus 5 - Qualcomm Snapdragon 800. After you said it I notice that indeed it's not smooth.

**Comment by werman** [comment]
I have profiled the issue and it's a combination of inflating viewholder (onCreateViewHolder method), synchronous reading from file and synchronous json decoding.

**Comment by segler-alex** [comment]
i have exynos on samsung galaxy s8 and no problems

**Comment by avently** [comment]
@werman do you know a way how we can improve performance?

**Comment by werman** [comment]
@avently 
- Layout inflation could be tackled from several sides: make station details hidden view inflated only when needed (via ViewStab), make global cache of inflated station views, inflate them asynchronous.
- Deserialize stations list once and store it in memory.
- Always deserialize in other thread.

This should solve most issues.
You can also profile yourself in Android Studio, maybe something will differ on your device:
image

**Comment by werman** [comment]
@avently Please look at suggestion #281

**Pull request merged**
