### PR TITLE
PlayerService is stopped when not needed anymore (and user left the app)

### LINKED ISSUE #71: Service "PlayerService" runs forever
if there is no radio station playing and i leave the app, the Service keeps running and does not stop.
please make the serivce stop itself when there is nothing to do.

### PR DESCRIPTION
**Pull request by zoff99**
fixes #71 

its a quick hack but works fine. Should you merge it, i guess you will clean it up a bit.

### CODE REVIEW

**Comment by zoff99** [comment]
are you considering this? need more infos?

**Comment by Wikinaut** [comment]
@zoff99 is this still relevant?

**Comment by Cormak** [comment]
Yes, every player should work like this. It shouldn't keep running in the background when not using it.

**Comment by segler-alex** [comment]
please push it again, i am not able to merge

**Comment by Wikinaut** [comment]
Superseded by https://github.com/segler-alex/RadioDroid/pull/248

**Pull request closed without merging**
