### PR TITLE
Re-run CI tests on open PRs when master changed

### PR DESCRIPTION
**Pull request by morckx**
This should run all CI tests on open pull requests whenever the master branch is updated.

@segler-alex : if you want to test or merge this, you first need to create a Personal Access Token here https://github.com/settings/tokens , if you haven't yet. 
Don't ask me about the necessary scopes. Apparently, I intuitively chose a sufficient superset, but I don't know if it is minimal.

Copy the token and add a new secret with the name _PAT_ here:
https://github.com/segler-alex/RadioDroid/settings/secrets and paste the token from the clipboard into the value field.

### CODE REVIEW

**Comment by werman** [comment]
Could you explain the benefit? How the changes in master affect PRs?

**Comment by morckx** [comment]
> Could you explain the benefit? How the changes in master affect PRs?

I don't know if it's really important. It can be used to find out whether a PR that is still open not only has no merge conflicts with the updated master, but also whether the build still works on the updated master with the respective PR and whether the tests still work.

**Comment by werman** [comment]
> but also whether the build still works on the updated master with the respective PR and whether the tests still work.

So you will be able to know if PR passes the tests if rebased onto master? In such case I could see it being useful.

**Comment by morckx** [comment]
> So you will be able to know if PR passes the tests if rebased onto master? In such case I could see it being useful.

Yes, that's the aim (and a clearer wording). In the course of the tests it is of course also checked if not the whole build breaks.

If we want to test this first, we can do this on my form at https://github.com/morckx/RadioDroid.
Breaking the master branch with test PRs is no problem there, it's just not easy to do it alone (with just on identity). OTOH: Testing it in real life here should also be no problem.

**Pull request merged**
