### PR TITLE
Update libraries: androidx, gradle, dependencies, target sdk

### PR DESCRIPTION
**Pull request by morckx**
So far (superficially) tested on APIs 28, 21, 16.

### CODE REVIEW

**Comment by werman** [comment]
No so fast =)
1) It would crash on Android 9 (API 28) due to changed network permissions which disallow http by default - https://github.com/werman/RadioDroid/commit/9663bf6268de448e749a1cb95e4a726eefd680cd#diff-a4a7c49a558393b9dae7c81d46f42aa2
2) Probably there is an issue with service permissions - https://github.com/werman/RadioDroid/commit/9663bf6268de448e749a1cb95e4a726eefd680cd#diff-c8cc2dd42271f2bf39c6aa81eb6a5529
3) My terribly huge branch with terribly descriptive commits already has this https://github.com/werman/RadioDroid/commits/feature/player-screen as a small part of overall changes, I just didn't expect anyone working on this... sorry.

**Comment by morckx** [comment]
> Not so fast =)

Well, AndroidStudio did almost everything automatically and instantaneously so that it took less than 10 minutes :)

> 1. It would crash on Android 9 (API 28) due to changed network permissions which disallow http by default - [werman@9663bf6#diff-a4a7c49a558393b9dae7c81d46f42aa2](https://github.com/werman/RadioDroid/commit/9663bf6268de448e749a1cb95e4a726eefd680cd#diff-a4a7c49a558393b9dae7c81d46f42aa2)

I don't think so. I'm using the target SDK change since three weeks on my Android 9 devices (one of them being my kitchen radio) and I've also set: `android:usesCleartextTraffic="true"` in the AndroidManifest directly.

> 2. Probably there is an issue with service permissions - [werman@9663bf6#diff-c8cc2dd42271f2bf39c6aa81eb6a5529](https://github.com/werman/RadioDroid/commit/9663bf6268de448e749a1cb95e4a726eefd680cd#diff-c8cc2dd42271f2bf39c6aa81eb6a5529)

Please have a look at my AndroidManifest-changes where I've also requested `android.permission.FOREGROUND_SERVICE`

> 3. My terribly huge branch with terribly descriptive commits already has this https://github.com/werman/RadioDroid/commits/feature/player-screen as a small part of overall changes, I just didn't expect anyone working on this... sorry.
> 
> P.S. The changes there snowballed out of control and I hope to merge them soon since most of it is working.

Yes, I've seen and tested some of your branches and thought of them while pushing this, but you're right that you couldn't expect someone working on this. I didn't either :)

Anyway, I think it would be great if you could push some of your changes here as WIP or as RFR (request for reviews).

**Comment by werman** [comment]
Uh, I dodn't know where I looked, sorry, your changes are correct.

I hope I'll post a PR soon when at least all functionality will be there even if not perfect.

**Comment by morckx** [comment]
Need to handle:
```
FATAL EXCEPTION: main
Process: net.programmierecke.radiodroid2, PID: 20144
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
at net.programmierecke.radiodroid2.FragmentPlayer$LifecycleCallbacks.onActivityStarted(FragmentPlayer.java:353)
at android.app.Application.dispatchActivityStarted(Application.java:230)
at android.app.Activity.onStart(Activity.java:1278)
```
I'm not 100% sure that this is related to androidx, but I've never seen this before.

**Comment by morckx** [comment]
Fixed via #469

**Pull request merged**
