### PR TITLE
WIP: Use Iconics cmd-calendar-edit icon for alarm week days selection

### LINKED ISSUE #743: Alarm only on weekdays
Hi, RD is my daily companion. But I need to start it manually, otherwise I will get an radio alarm at 06:00 on every weekend.

Could you please add a day mask to flag at which days the alarm is enabled?

### PR DESCRIPTION
**Pull request by morckx**
Partially fixes #743

I think it's better, but I'm not completely happy with this.

### CODE REVIEW

**Comment by morckx** [comment]
Screenshot_20200303-223208_RadioDroid

**Comment by werman** [comment]
Hmmm, looking at the clock app in my phone I think the solution is easy:

image

When checkbox is checked day appear, all selected by default. That's clear and unambiguous. To be honest I don't like icons

**Comment by morckx** [comment]
Yes, much better. I also looked at mine (AOSP) first, but the AOSP variant doesn't look much better and we'd have to migrate to `RecyclerView`. Maybe we should reuse some existing open source layout here. Yours looks good to me.

**Comment by segler-alex** [comment]
in WIP too long, closing
please create another PR if you want to work on it.

**Pull request closed without merging**
