### PR TITLE
Use JobIntentService instead of IntentService for PlayerService 

### LINKED ISSUE #807: Not allowed to start service Intent: … : app is in background
Despite https://github.com/werman/RadioDroid/commit/ad607f8116991e8da3e488646530fca93f132e4e I'm still getting this error about once a day:

```
[04-25 23:56:00.542 3935:3935 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: net.programmierecke.radiodroid2, PID: 3935
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=net.programmierecke.radiodroid2/.service.PlayerService (has extras) }: app is in background uid UidRecord{5479c41 u0a411 TPSL idle procs:1 seq(0,0,0)}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=net.programmierecke.radiodroid2/.service.PlayerService (has extras) }: app is in background uid UidRecord{5479c41 u0a411 TPSL idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
	at android.app.ContextImpl.startService(ContextImpl.java:1571)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at net.programmierecke.radiodroid2.service.PlayerServiceUtil.bind(PlayerServiceUtil.java:47)
	at net.programmierecke.radiodroid2.ActivityMain.onCreate(ActivityMain.java:168)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
```
I have not yet examined it in detail again, but I wanted to document it here.

### PR DESCRIPTION
**Pull request by morckx**
This should fix #807, but requires some testing. 
Maybe the problem is just moved to another place.

### CODE REVIEW

**Comment by werman** [comment]
I definitely think this is shifting the issue somewhere else. 

However I don't understand the error in question. Is there any steps to reproduce, anything you do in particular when it happens?

**Comment by morckx** [comment]
> I definitely think this is shifting the issue somewhere else.

So far, I have some hope that if the issue is moved elsewhere, at least it no longer leads to a crash of the player service. But I have to wait a few days first and have a look at the logs.

> However I don't understand the error in question. Is there any steps to reproduce, anything you do in particular when it happens?

I haven't managed to reproduce it quickly. I think it happens often when RadioDroid  has been playing for a couple of hours in the background with the foreground activity  already killed and you try to restart the foreground activity (I think) by tapping on the notification.

I have collected the logs for 11 days and the crash happend 21 times during that period.

With JobIntentService im running RadioDroid since 1.5 days without crash, but of course that doesn't mean anything.

**Comment by morckx** [comment]
I guess, this really seems to solve the problem after all. Not a single RadioDroid crash (or error-level logcat entry) in the last 4 days.

If there is still a trace of the problem, it's only as a warning, but I only found it once:
```
[05-10 22:59:42.236 1399:4966 W/ActivityTaskManager]
startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=net.programmierecke.radiodroid2/.ActivityMain (has extras) }
```


I will keep watching this for a while, but I am now pretty sure that using `JobIntentService'` brings a significant improvement.

**Comment by morckx** [comment]
No more crashes, not a single one in 7 days testing. Fixes #807 and is ready to merge, I guess.

**Pull request merged**
