### PR TITLE
Add github action to perform CI tests on pushes and pull requests

### PR DESCRIPTION
**Pull request by morckx**
I don't know if this is already perfectly configured, but it should already help avoiding issues like #810 as pull requests will be automatically checked and marked accordingly.

### CODE REVIEW

**Comment by Wikinaut** [comment]
I **do** hope so, too. Many thanks. The commit needs to be reverted, please.

**Comment by morckx** [comment]
Seems to work and is extremely quick as well.

**Comment by morckx** [comment]
> I **do** hope so, too. Many thanks. The commit needs to be reverted, please.

I already made a PR to fix the problem in #806 and asked the author to fix the problem in a review before. 

This PR should also avoid the problem in the furure.

**Comment by Wikinaut** [comment]
We should never allow again to merge untested commits into the master branch, please.

**Comment by morckx** [comment]
> We should never allow again to merge untested commits into the master branch, please.

When this PR gets merged everybody can immediately see if a PR breaks a build or fails on the tests (currently only very few unit tests)

**Comment by werman** [comment]
Cool, we definitely should check if it builds. I also hope we would able able to smoothly integrate UI tests I'm writing....

**Comment by morckx** [comment]
> Cool, we definitely should check if it builds. I also hope we would be able to smoothly integrate UI tests that I'm writing....

Yes, also Espresso tests should be no problem with github actions. Actually, the current configuration runs all tests by `./gradlew test  --stacktrace`. I should change the messages accordingly...

**Pull request merged**
