### PR TITLE
Fix wrong string values for giving_up_resume

### PR DESCRIPTION
**Pull request by morckx**
This bug was already introduced in 4703dce0f1657c7a803cb943acf0db0a772f7199 and had often confused me.

I don't know if Chinese, Danish and Indonesian are also affected.

### CODE REVIEW

**Comment by zo-shin** [comment]
Why do you think "ignore" is a bug?

**Comment by morckx** [comment]
> Why do you think "ignore" is a bug?

Because the attempt to resume is not ignored but given up when the `settings_resume_timeout` is reached.

**Comment by zo-shin** [comment]
I feel "ignored" and "abandoned" mean the same.

**Comment by zo-shin** [comment]
And "give up" and "ignore" mean the same.

**Comment by morckx** [comment]
> And "give up" and "ignore" mean the same.

No, _to ignore_ comes from the Latin _ignorare_. It is used in many Indo-European languages and can mean _not to know_ or _not to pay attention to_. (Whereas _give up_ and _abandon_ share a meaning feature of stopping and do not have the _not knowing_ or _not paying attention to_ meanings.)

**Comment by zo-shin** [comment]
In that case, can we use a more common word “stopped” instead of “abandoned”?

**Comment by morckx** [comment]
> In that case, can we use a more common word “stopped” instead of “abandoned”?

"stopped" is too ambiguous because it more an agent outside the player with a higher chance than "abandoned". The best (most to the and most idiomatic) variant IMHO was my initial "Giving up attempt to..." or something like that.

**Comment by morckx** [comment]
> > In that case, can we use a more common word “stopped” instead of “abandoned”?
> 
> "stopped" is too ambiguous because it allows an agent outside the player with a higher chance than "abandoned". The best (most to the point and most idiomatic) variant IMHO was my initial "Giving up attempt to..." or something like that.

OK, I changed it back to the very initial "Giving up attempt ..." for English.

**Comment by zo-shin** [comment]
“Give up” does mean “stop doing”, and it should be “Attempt to resume playback stopped”.

**Comment by morckx** [comment]
> “Give up” does mean “stop doing”, and it should be “Attempt to resume playback stopped”.

I agree with you so far that "give up" and "stop" share some aspects of meaning, but they do not mean the same. I wouldn't even call them synonyms.

Following Grice's conversational "Maxim of Manner", in this case I would choose "give up" before "abandon" before stop.

One particular reason why "... stopped." would not be very appropriate here, I have have already mentioned: It might be misinterpreted as an impersonal passive, which is particularly misleading in this case. The "Giving up" is admittedly a bit more emotional, but I think that fits perfectly after 2 minutes of retrying :) and in case of English is absolutely common in this context.

Normally I wouldn't care about all this, but I've put some work into both our ways of retrying after errors with the goal of a good user experience, which includes a good enough comprehensibility of what is actually going on, in order to take appropriate action, i. e. increase a specific timeout in this case.

**Comment by zo-shin** [comment]
1 - According to some authoritative dictionaries like *Longman Dictionary of Contemporary English* and *Oxford Advanced Learner's Dictionary*, “give up sth” and “stop doing sth” mean exactly the same. Besides, “stop” is more snappy, more common than “give up”.
2 - The continuous tense should not be used because it’s something just happened, not something happening now.

**Comment by morckx** [comment]
> 1 - According to some authoritative dictionaries like _Longman Dictionary of Contemporary English_ and _Oxford Advanced Learner's Dictionary_, “give up sth” and “stop doing sth” mean exactly the same. Besides, “stop” is more snappy, more common than “give up”.

That's not exactly true. They just share some parts of their meaning. In addition, dictionaries can only cover some aspects of meaning in their necessarily short definitions. Moreover, there is still the problem with the agentless passive misinterpretation you have not addressed.

> 2 - The continuous tense should not be used because it’s something just happened, not something happening now.

Simultaneity is only one aspect of use of present continuous (expressing some emotiveness is another) and it happens here almost simultaneously.

Sorry to be so know-it-all here, but I'm not only the author of the code and pursue certain goals with the messages but also, a researcher and lecturer in linguistics :)

Anyway, "abandoned" would be okay for me here, too. I had brought the "Giving up..." back into the game, mainly because I assumed that you wouldn't like the "abandoned".

If native speakers or linguists specialized on English stand up for "... stopped" here, I will gladly admit defeat.

Most important for me is to fix to correct "ignored" before a new beta-release is released.

**Comment by zo-shin** [comment]
1 - Sharing ideas is not a problem. Truth won’t become lie because of being shared. The key is whether it is reliable.
2 - “Give up” is not durative. That’s why we usually heard “**I gave up the job**” more than “**I’m giving up the job**”. First, “the attempt to resume playback” didn’t happen, then the attempt can be called abandoned / stopped. They didn’t happen simultaneously, even just after 0.01 sec. Whichever word it will be, it shouldn’t be in continuous tense.

**Pull request merged**
