### PR TITLE
Build with circleCI

### PR DESCRIPTION
**Pull request by zoff99**
add commands to build on circleCI

### CODE REVIEW

**Comment by zoff99** [comment]
https://circleci.com/gh/zoff99/RadioDroid/6#artifacts

capture_app_running

**Comment by segler-alex** [comment]
interesting, what is this? how does this help?

**Comment by segler-alex** [comment]
why would i want to build this in the cloud, if build on my home pc just takes 5 seconds?

**Comment by zoff99** [comment]
so everybody else can fork and build, and other people do NOT need any server to build
also it's free

**Comment by zoff99** [comment]
it's not for release builds, but for other people to quickly build and test.
also it will automatically test all PR requests here (if you once login to circleCI)

**Comment by segler-alex** [comment]
nobody needs a server to build, you just need android studio. you need android studio to do the programing anyway. am i missing something here?
when people make additions, they are working in android studio anyway, so they can make builds in 5 seconds themselves.
if i have to login for builds to work, how would that be different to the current situation?
this sounds just like more works, for no benefits at all :)
am i wrong?

**Comment by segler-alex** [comment]
don't get me wrong, i am interested, but i don't see why at the moment....

**Comment by zoff99** [comment]
it's up to you. use it or don't :-)

i use circleCI to automatically build every fork and every commit for me.
it acutally takes a big load from me.

**Comment by segler-alex** [comment]
how does it take work from you? you have to build it anyway. and do the checking yourself. and upload to google or fdroid yourself....

**Comment by zoff99** [comment]
no

**Comment by zoff99** [comment]
why would you need android studio to just add or fix translation strings?
also there are many reasons to use CI.
but thats another topic.

anyway, i use it, and i like to share.

**Comment by segler-alex** [comment]
i use CI at work. i think it is much help there. build there takes 5-10 minutes.
but i don't see it here. i will merge for now, it does not harm.

**Pull request merged**
