### PR TITLE
remove dependabot workflows

### PR DESCRIPTION
**Pull request by segler-alex**
we do not need it, it is completely useless in my opinion. i never use the provided pull requests, much too dangerous

### CODE REVIEW

**Comment by vdbhb59** [comment]
Agreed.
May I also request: Is there a possibility for me to be added to the RD Repo? I would then not have to request PR/MR. I may also be able to help in other ways.

**Comment by segler-alex** [comment]
your big PR did the following:
grafik
which made the tests fail.

**Comment by vdbhb59** [comment]
> your big PR did the following: grafik which made the tests fail.

I did a lot of changes. One code did break it, but does that make it so bad.: -(
I am trying to help here.

**Comment by segler-alex** [comment]
I made errors too, but this tells me something. I have to check PullRequests better in the future and I think multi-eyed principle is a good one and it should stay. So please keep doing Pullrequests.
I still have the problem that 2 of the tests in the pipeline do not run through and I do not know why exactly.

**Comment by vdbhb59** [comment]
There are many changes needed for upgrade of build systems. I too am not sure where Git is giving errors. I can try and check tomorrow. But do not believe the code has any issues as such. More probably to do with compatibility.

**Comment by vdbhb59** [comment]
I tried to edit my previous comments, but by mistake deleted it. :-(

**Pull request merged**
