### PR TITLE
Fix missing icons 2

### LINKED ISSUE #729: Some icons are invisible after libraries update
image
image

At least on API 28

@morckx

### PR DESCRIPTION
**Pull request by morckx**
Fixes #729 

Iconics 4.0.1 -> 4.0.2 was the culprit. 

@werman : please have a look if it works.

### CODE REVIEW

**Comment by werman** [comment]
I think here is an explanation https://github.com/mikepenz/Android-Iconics/issues/479

**Comment by werman** [comment]
It seams we should use custom views https://github.com/mikepenz/Android-Iconics#custom-views

**Comment by morckx** [comment]
Thanks, that explains it. I think we don't even use `IconicsLayoutInflater2` and can just skip it.

**Comment by morckx** [comment]
@werman: does this work for you?

**Pull request merged**
