### PR TITLE
Show star icons on favorites

### PR DESCRIPTION
**Pull request by Wikinaut**
This commit adds 

+ a green transparent icon with a white border
+ to all station icons of **starred** stations

### CODE REVIEW

**Comment by h3298** [comment]
It is pointless and redundant to show stars on the icons which are displayed in the starred panel.  (And the "Starred" panel should be renamed as "Favorites")

**Comment by Wikinaut** [comment]
I coded that, and you are right.

I was too lazy to remove the "fav-star" there, and also thought it would be better to "harmonize" the view. Will do this later, okay?

**Comment by h3298** [comment]
You could put the star on the menu title line for clarity

**Comment by Wikinaut** [comment]
@h3298 I considered a patch of the corresponding code line https://github.com/segler-alex/RadioDroid/blob/aaecbf42de728242deb4b5ac121b9b5bafad1747/app/src/main/java/net/programmierecke/radiodroid2/adapters/ItemAdapterStation.java#L285 but found this currently quite difficult.

In addition: currently, the greenish transparent "star" symbol follows the status ("is favorite") of the black favorite star inside the station detail view. Not showing the greenish star but showing the black star (because that specific station _is_ a favorite, when it is shown on the favorite page) would be inconsistent.

**Pull request merged**
