### PR TITLE
Show stations during search as query being typed

### PR DESCRIPTION
**Pull request by Wikinaut**
I tested https://github.com/werman/RadioDroid/commit/6a55b03c3a0e21b1e2cd2dbc0ffa68b1e74ed6f2 and propose to merge this.

Fixes https://github.com/segler-alex/RadioDroid/issues/309

### CODE REVIEW

**Comment by werman** [comment]
There is one issue left there, search by tag doesn't work, meaning when you click on tag - search will do nothing. And I didn't test refreshing when search fails.

**Comment by werman** [comment]
And I will be away for two weeks, so I won't be able to fix this until then.

**Comment by Wikinaut** [comment]
I checked that, it a so tiny issue, I think, this is **not** a blocker for merging your feature branch into master.

**Comment by Wikinaut** [comment]
(closing this pull request until https://github.com/werman/RadioDroid/issues/1 is fixed, a small issue.)

**Comment by Wikinaut** [comment]
As I run this code together with master since almost two weeks without any problems, I suggest now to merge this into master.

**Pull request merged**
