### PR TITLE
WIP: RFC: Some thoughts on the approach

### PR DESCRIPTION
**Pull request by andrewshadura**
As I mentioned in #901, I’m attempting to gradually work on the conversion from Java to Kotlin, in a bottom-to-top fashion.

My first attempt was `station.live.ShoutcastInfo`/`station.live.StreamLiveInfo`, but it turned out `@Parcelize` is currently broken in Kotlin, so those classes aren’t worth porting, since it’s `@Parcelize` that would reduce the amount of boilerplate the most.

So I decided to try converting other bits. `station.live.metadata.*` was mostly easy, but e.g. `service.PlayerServiceUtil` is tricky. I don’t like flipping multiple nullables as the Java code does, so I attempted to bring a pattern I learnt from Rust, so I’ve put two parts of the state into an Rust-enum-like type.

Please let me know what you think about it.

P.S. I have not yet tested this.

cc @werman

### CODE REVIEW

**Comment by werman** [comment]
Regarding `@Parcelize`, I think we don't need to use AIDL; it only complicates things and adds indirection. I think it's just that no one got to remove it. 

For our case (service in the same process as application) Android documentation recommends extending `IBinder` interface and use it directly https://developer.android.com/guide/components/bound-services#Creating. This should be much simpler. And most of `PlayerServiceUtil` would be gone.

**Comment by andrewshadura** [comment]
Right, that part is well outside of my Android knowledge at the moment. I guess it will take some time for me to learn about it :slightly_smiling_face:

**Comment by andrewshadura** [comment]
However, I’m still interested to hear about the pattern I used.

**Comment by werman** [comment]
> I don’t like flipping multiple nullables as the Java code does, so I attempted to bring a pattern I learnt from Rust, so I’ve put two parts of the state into an Rust-enum-like type.

I agree here with you and it is more safe.

**Comment by segler-alex** [comment]
in WIP too long, closing

**Pull request closed without merging**
