### PR TITLE
bump version 0.46

### PR DESCRIPTION
**Pull request by Wikinaut**
forgot to bump the version number in previous pr

### CODE REVIEW

**Comment by Cormak** [comment]
@Wikinaut Why are you guys skipping so many versions? Google Play only has 0.37.

**Comment by Wikinaut** [comment]
Because I can... and because in each of the versions in between I added unique new features, which were not yet published on Google Play (ping @segler-alex ).

**Comment by Wikinaut** [comment]
@segler-alex When do you intend to upgrade the Google-Version?

**Comment by Cormak** [comment]
@Wikinaut hey, if you're adding more to the app, which it definitely needs, I'm not complaining. I'm just wondering what is going on with the versioning. Are we going to get a 0.50 release on Google Play? 1.0? Is this going to be a massive new release?

**Comment by Wikinaut** [comment]
I am not the owner ( @segler-alex  has not answered me when he is upgrading. )

**Comment by segler-alex** [comment]
i pushed 0.46 to the google beta channel and to fdroid

**Pull request closed without merging**
