### PR TITLE
WIP: Add option to restart playback on headphones re-connection

### PR DESCRIPTION
**Pull request by werman**
Will resume playback only if it was paused by previous disconnect of headphones.

Closes: #628

@JensKorte Would you be able to test it? Or anyone else.

### CODE REVIEW

**Comment by JensKorte** [comment]
Where can I find an apk?

**Comment by werman** [comment]
@JensKorte I'll compile it later today.

**Comment by werman** [comment]
Try: 
[RadioDroid-free-debug-DEV-0.79-fa8d78a.zip](https://github.com/segler-alex/RadioDroid/files/4000747/RadioDroid-free-debug-DEV-0.79-fa8d78a.zip) - unpack .apk and install it. It would be installed alongside the RadioDroid you already have. The option to restart playback is under "Player" settings group.

**Comment by JensKorte** [comment]
I can't install it. Normally I get "file wasn't installed" once I got "file too big". There was more than 1,5GB free and I also removed some files.

**Comment by JensKorte** [comment]
Galaxy S5 with recent lineageos

**Comment by werman** [comment]
Sorry, fixed this: 
[RadioDroid-play-release-0.79-9d49217.zip](https://github.com/segler-alex/RadioDroid/files/4000792/RadioDroid-play-release-0.79-9d49217.zip)

**Comment by zo-shin** [comment]
There are some problems in the beta release, and I'll make a report later.

**Comment by zo-shin** [comment]
By the way, there are two problems I can’t confirm.
1 - It seems that the lastfm API doesn’t work at all because I can’t see any album art from it.
2 - Click any items in **tags**, **countries** or **languages**, there will be no result in **search**.

**Comment by JensKorte** [comment]
It works, but I found a special behaviour: RD in foreground or background disconnect stops the player, connecting starts the player. RD playing in FG or BG disconnecting the plug and switching it to BG or FG, connecting the plug, music doesn't start.

How about an additional pop up message for 3 seconds like "Plug-in to restart playing".

**Comment by werman** [comment]
@JensKorte This behaviour would be fixed by #636

> How about an additional pop up message for 3 seconds like "Plug-in to restart playing".

I don't think this popup will be useful in any way. User who enabled the option will know what to expect and in most cases user won't disconnect the headset while looking at the app screen.

@zo-shin Open 

> Redesign MPD Menu
> 1 - The your server string is redundant.

Looks like it.

> 2 - The enable MPD and add MPD server commands are at the left top instead of centered, and there is too much space in the menu when no server is added.

I don't think they should be centered, maybe moved to right as in popups - https://material.io/components/dialogs/#

The space - I don't know what to do with it, removing it will make popup even weirder. 

> 3 - It’s not very necessary to show the two commands in capital letters.

https://material.io/components/dialogs/#

> By the way, there are three problems I can’t confirm.
> 1 - It seems that the lastfm API doesn’t work at all because I can’t see any album art from it.

I think I see this too, something goes wrong.

> 2 - Click any items in tags, countries or languages, there will be no result in search.

It was introduced by #626 

> 3 - Enable external player doesn't work.

Will check

**Comment by zo-shin** [comment]
By the way, does **headset** and **headphones** refer to the Bluetooth ones or the cable ones?

**Comment by werman** [comment]
> By the way, do **headset** and **headphones** refer to the Bluetooth ones or the cable ones?

I this case both wired and wireless. But I also have confusion over terminology.

**Comment by zo-shin** [comment]
Will you agree if I change **headset** and **headphones** to **earphones**?

**Comment by werman** [comment]
Unfortunately the meaning of earphones is still not encompassing enough from my perspective, however yes I agree that using different words for the same thing as I did, should be fixed.

On the second thought we can do as Poweramp, see https://www.androidmediaplayers.com/resume-playback-when-wired-headset-is-inserted-for-poweramp-music-player/

Thus having three options:
- Pause On Headset Disconnect with better description
- Resume On Wired Headset
- Resume On Bluetooth

**Comment by zo-shin** [comment]
OK. Your idea is better.

**Pull request closed without merging**
