### PR TITLE
A Few Fine Adjustments

### PR DESCRIPTION
**Pull request by zo-shin**
A few fine adjustments
Fixed the invalid GPLv3 URL

### CODE REVIEW

**Comment by werman** [comment]
Two minor suggestions:
- Could you squash url fixes into one commit?
- It would be better to have something more descriptive than "A Few Fine Adjustments".

Just to have better commits history.
Thanks!

**Comment by zo-shin** [comment]
Thanks for your attention. The URL fix involves seven different string files, and I don't know how to combine them into one. I'll try to use more straightforward words to describe my pull request next time.

**Comment by werman** [comment]
Since you already made the commits you can find how to squash them here: https://stackoverflow.com/a/51049029

If you are in process of making commits and want to add something to the last one you can use git --amend, see https://www.atlassian.com/git/tutorials/rewriting-history

**Comment by zo-shin** [comment]
Thanks a lot.

**Pull request merged**
