### PR TITLE
Themes support, circular icons, compact style, backstack support

### LINKED ISSUE #32: Version 0.13: back button closes App and views (looks strange)
Was it intended ? A feature, or a bug ?

How to reproduce:
- start RadioDroid
- goto settings
- goto About ("Über")
- click "back button" (Android)

App shuts down, uh.

### LINKED ISSUE #46: FR: Dark theme
Hi
It would be nice if the app offers dark theme.

thanks

### LINKED ISSUE #230: [Improvement] Change the notification icon according to play or pause status
Icon in the notification should reflect the Player status.

### LINKED ISSUE #257: [Feature Request] Add station icon to now playing notification?
Right now, the only thing the notification is missing is the same station icon from the station listings. That would make the notification feel complete and modern. We only have stop and pause buttons so there should be plenty of room for it.

### PR DESCRIPTION
**Pull request by avently**
Hello.
Implemented some cool things here.
All information about commits in a description of commits.
In short:
- themes support. Only dark theme for now but you can easily add any amount of themes because code is ready for that.
- square icons can be replaced with circular icons.
- more compact radio item can be selected in settings too.
- backstack support is here. Finally. 
- icon in notification.

THis PR closes #46 closes #257 closes #230 closes #32

### CODE REVIEW

**Comment by avently** [comment]
Preview app. Just rename to .apk
[RadioDroid-free-debug-DEV-0.48-3581f3a.zip](https://github.com/segler-alex/RadioDroid/files/1591174/RadioDroid-free-debug-DEV-0.48-3581f3a.zip)
screenshot_20171228-151843

**Comment by werman** [comment]
Theme support is nice! 
Shouldn't the dark theme also have dark header? And some icons are dark while they should be light, but that's not the point of these changes - just my thoughts for further improvements.

The two step load in of icons with Picasso is intended since I want to display cached images immediately. With your changes, please check how it works with cached images with unstable connection and without connection.

**Comment by avently** [comment]
>Shouldn't the dark theme also have dark header?

How to change statusbar color before API 21? Could find the way to do it. It stays blue after header changes its color

**Comment by werman** [comment]
Changing status bar color was introduced in API 21 so it won't work on earlier APIs.

**Comment by avently** [comment]
Made changes to actionbar and icons. Looks better. Hope it will not make things bad on older APIs

**Comment by segler-alex** [comment]
thank you!!

**Comment by werman** [comment]
@avently Even though this pull request is merged please check this:

> The two step load of icons with Picasso is intended since I want to display cached images immediately. With your changes, please check how it works with cached images with unstable connection and without connection.

**Comment by avently** [comment]
@segler-alex you too! I really like how code is organized. Everything on its place and can be easily edited. 

I found that I forgot to change icon tint color for alarm item icons. 
Can you add 
```
android:tint="?attr/iconsInItemBackgroundColor"
```
To two icons in list_item_alarm?

**Comment by avently** [comment]
@werman i'm not experiencing any problems with that implementation. Even on 2G internet. If you have it we can discuss.

**Comment by werman** [comment]
@avently Ok, thanks for checking, I'll check it later, I just remember that I had issues with it.

**Comment by avently** [comment]
This is the final commit with missing color for alarm
https://github.com/avently/RadioDroid/commit/260a21ca11489076a60814b0b7d126d9521f56b2

**Comment by Cormak** [comment]
@avently This PR is amazing. You made Radiodroid come much closer to feeling like a modern app.

**Pull request merged**
