### PR TITLE
Respond to media buttons when restarted

### PR DESCRIPTION
**Pull request by morckx**
Listen to ACTION_MEDIA_BUTTON intents that android sends when it
restarts the last active media session.

### CODE REVIEW

**Comment by werman** [comment]
Cool, this should work. Also could you take a look at https://developer.android.com/guide/topics/media-apps/mediabuttons#restarting-inactive-mediasessions ? Maybe that magic incantation will work, this whole documentation is a very fine spaghetti...

**Comment by morckx** [comment]
> Cool, this should work. Also could you take a look at https://developer.android.com/guide/topics/media-apps/mediabuttons#restarting-inactive-mediasessions ? 

Yes, that's exactly where you pointed me to and where I looked it up.

**Comment by werman** [comment]
I'm talking about:

> This behavior is automatically enabled when you use MediaSessionCompat. If you use the Android framework's MediaSession or Support Library 24.0.0 through 25.1.1 you must call setMediaButtonReceiver to let a media button restart an inactive media session.
> 
>  `mediaSession.setMediaButtonReceiver(null)` 
> 

Maybe it's enough to do this?

**Comment by morckx** [comment]
I thin this is exactly the opposite of what we want:

> You can disable this behavior in Android 5.0 (API level 21) and higher by setting a null media button receiver: 

If I call `mediaSession.setMediaButtonReceiver(null)`the media session is not restarted the next time when I press play on my bluetooth box.

**Comment by werman** [comment]
Ah, sorry, don't mind it. Thanks!

**Comment by morckx** [comment]
Ready to merge, as far as I'm concerned.

**Comment by segler-alex** [comment]
thank you!

**Pull request merged**
