### PR TITLE
Revert "Italian translation"

### PR DESCRIPTION
**Pull request by Wikinaut**
Reverts segler-alex/RadioDroid#894

Your commit contains a lot of unescaped ' characters which break the code.

### CODE REVIEW

**Comment by werman** [comment]
Couldn't we just escape them though?

**Comment by Wikinaut** [comment]
of course. But in my view, that's work to be done by the original author of that commit.

**Comment by werman** [comment]
Yes, the original author should do this, but if they won't respond it would be better for us just to fix it.

I think having a hard-coded list of languages in the tests - isn't the greatest idea after all... I'll see what could be done with it.

**Comment by werman** [comment]
Ah, it didn't even compiled and thus didn't pass any test, why it was even merged... 

However it's still would be worth to not have a hard-coded array of localizations.

**Comment by Wikinaut** [comment]
>  didn't pass any test, why it was even merged.

How can this happen? Should not anymore.

**Comment by werman** [comment]
I guess, segler-alex didn't look at the tests status. And we couldn't make a hard gate on passing all tests because UI tests could be a bit unstable for the reason I'm not exactly sure (e.g. see a failing test in this PR).

**Comment by andrewshadura** [comment]
#902 supersedes this pull request.

**Pull request closed without merging**
