### PR TITLE
Add some very very basic Android TV support

### PR DESCRIPTION
**Pull request by andrewshadura**
As the title suggests, this is not a complete fix for #900, but only the absolute minimum to make the app usable on Android TV:
* a banner
* a change in the manifest

### CODE REVIEW

**Comment by andrewshadura** [comment]
Obviously, this PR fails because of the breakage PR #902 fixes.
I’ll just rebase this one on top of it.

**Comment by werman** [comment]
Thank you, works in an emulator.

About the controls, I made some changes for accessibility some time before, however I think there is still some weird selection order, and the most troubling is the lack of visual feedback on half of the elements. Also full-screen played looks awful in landscape layout...

**Comment by andrewshadura** [comment]
It'd probably be best to follow Google's advice and have a separate activity in the long run.

**Review by werman — APPROVED** [review]

**Comment by andrewshadura** [comment]
@segler-alex, I wonder if you could pretty please tag and upload a release, so that RadioDroid is at least installable on Android TV :slightly_smiling_face:

**Comment by morckx** [comment]
It works pretty well for me and and it is always annoying to install apps via sideload on Android TV. I am also curious if there any additional reviews for Android TV play store approval.

**Comment by andrewshadura** [comment]
@morckx, see here: https://developer.android.com/docs/quality-guidelines/tv-app-quality

**Pull request merged**
