### PR TITLE
set version to 1.0.0

### PR DESCRIPTION
**Pull request by Wikinaut**
I have no idea, if you like that but I want to propose to go for "Version 1.0.0" now. If you don't like it, pls. just dismiss the pull request.

### CODE REVIEW

**Comment by werman** [comment]
I think we indeed could make it 1.0.0 soon. I don't see any important things not implemented (beside Android Auto but it's not that trivial). So when we hammer out some annoying bugs - we can make it 1.0.0.

**Comment by zo-shin** [comment]
I think there should be something to do on #395 #396 #398 #399 #440 #442 #497 #528 before the major update.

**Comment by Wikinaut** [comment]
@zo-shin Ok, pls. let me add this https://github.com/segler-alex/RadioDroid/issues/309 to the list. Shouldn't we better make up an extra blocker issue comprising all the mentioned issues?

**Comment by werman** [comment]
Could you comb the issues and sort them by priority, we won't be able to fix everything but we don't want crashes or showstoppers.

**Comment by Wikinaut** [comment]
@werman I don't know who maintains the repo, but perhaps it would be helpful to give me and a few other people the permission to assign labels to the issues.

**Comment by Wikinaut** [comment]
Labels like "blocker", "suggestion" and a few more.

**Comment by zo-shin** [comment]
#497 #528 should be resolved first because they make the app crash.

**Comment by segler-alex** [comment]
i will try to give you more rights, i read github supports teams.

**Comment by segler-alex** [comment]
i think i have to move the project to the team account, so that i can invite you and give you more rights. this could affect currently forked connections, but i will read on that further

**Comment by Wikinaut** [comment]
@segler-alex Hi, you made me member of two "organisations", but I still cannot assign labels to issues here. Can you?

**Pull request closed without merging**
