### PR TITLE
Added mini player at the bottom of the screen

### PR DESCRIPTION
**Pull request by avently**
- removed player status from the drawer.
- added a view located at the bottom of the every screen with play/pause/record controls and a current status of a playback (station, track title, location of a recorded track, etc).
- removed some unused action/elements from status page.
- simplified the interface.
- added an icon to the player and possibility to place it even in notiification.

It is not a final commit. I uploaded it now just to discuss it with you. I also need to remove unused code and to think about where to place alarm button. And how to place an image into a notification. And how to get last played radio station and add it to the player's view after start up.

What do you think?

### CODE REVIEW

**Comment by werman** [comment]
Hi, from description seems nice, could you add some screenshots?

**Comment by avently** [comment]
@werman hi
screenshot_20171226-145518
screenshot_20171226-145504

**Comment by werman** [comment]
Thanks,
From UI standpoint the playing station UI looks good.

About recording a station:

Does record UI replace playing station UI? I think it would be better to place recording indicator in playing station UI with stop button because I don't see a point in radically changing mini player's look when recording something. 

Also I ultimately want to make the player page with current album art (if supplied by station), all playback info, record/alarm buttons and playback history, so I propose to left status page with its buttons for now (since there is probably no place for record and alarm buttons in mini player).

> And how to get last played radio station and add it to the player's view after start up.
You can use HistoryManager.

**Comment by avently** [comment]
>Does record UI replace playing station UI? 

Recording UI becomes visible after you click on the mini player and hides with another click.

>I think it would be better to place recording indicator in playing station UI

I tried but it looks weird and uncomfortable just because people don't use recording feature often and this button will eat space (there is no more space for something). Also there will be no place for text about recorded track (it is useful for newbies).

>Also I ultimately want to make the player page with current album art (if supplied by station)

Yes, it would be cool but not in the current implementation. I thought about a fragment in a half of a height of a screen (just because radio don't need to many controls like audio player do) that will be displayed after a click on mini player. I don't think i can do it good. Maybe someone will create it after this PR or I'll create someday.

>I propose to left status page with its buttons for now 

The mini player was made of that status page. So you can't use it like before.

>there is probably no place for record and alarm buttons in mini player

You mean timer. Timer can be located in action bar. But I need to create a window that can be used to set timer.

>You can use HistoryManager.

thanks, i'll see

**Comment by werman** [comment]
> Recording UI becomes visible after you click on the mini player and hides with another click.
Seems good for me at the moment.

> I tried but it looks weird and uncomfortable just because people don't use recording feature often and this button will eat space (there is no more space for something). Also there will be no place for text about recorded track (it is useful for newbies).

I meant placing button only if recording is in the progress, but with your current implementation it is indeed no need in it there. But I do think there should be some indicator of ongoing recording there to eliminate any possible confusion.

> Yes, it would be cool but not in the current implementation. 
Sorry for confusion, it's only something I want to implement in future, it's far beyond the current changes. If you will be willing to work on it later I can help with any issue which may arise.

> The mini player was made of that status page. So you can't use it like before.
You are right, I was just confused where recording is started and thought that some separate UI may be needed. I don't have an ability to compile and see the changes so I just assume some things.

> You mean timer. Timer can be located in action bar. But I need to create a window that can be used to set timer.
Yes.

**Comment by avently** [comment]
Uploaded an apk with the latest changes. Just rename .zip to .apk
[RadioDroid-free-debug-DEV-0.48-b5cd300.zip](https://github.com/segler-alex/RadioDroid/files/1587737/RadioDroid-free-debug-DEV-0.48-b5cd300.zip)

**Comment by segler-alex** [comment]
looks great! thanks

**Pull request merged**
